# Generated by Django 3.0.7 on 2021-08-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powercons_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Staff'), (3, 'Client')], default=1, max_length=10),
        ),
    ]
