# Generated by Django 3.0.7 on 2021-08-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powercons_app', '0002_auto_20210805_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='contract_name',
            field=models.CharField(default='NA', max_length=30, unique=True),
        ),
    ]
