# Generated by Django 3.0.7 on 2021-08-06 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powercons_app', '0003_contracts_contract_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('service_type', models.CharField(max_length=20)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powercons_app.Suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('client_id', models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='powercons_app.Clients')),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('part_type', models.CharField(max_length=20)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powercons_app.Suppliers')),
            ],
        ),
    ]
