# Generated by Django 3.0.7 on 2021-08-06 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powercons_app', '0004_parts_payments_services_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powercons_app.Clients')),
            ],
        ),
    ]
