# Generated by Django 3.0.7 on 2021-08-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powercons_app', '0006_auto_20210809_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='part_type',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='timeframe',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_type',
        ),
    ]
