from django.urls import path, include
from . import views
from .import adminviews#, StaffViews, StudentViews


urlpatterns = [
    path('', views.loginPage, name="login"),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('get_user_details/', views.get_user_details, name="get_user_details"),
    path('logout_user/', views.logout_user, name="logout_user"),
    # admin dashboard
    path('admin_home/', adminviews.admin_home, name="admin_home"),
    path('add_staff/', adminviews.add_staff, name="add_staff"),
    path('add_staff_save/', adminviews.add_staff_save, name="add_staff_save"),
    path('manage_staff/', adminviews.manage_staff, name="manage_staff"),
    path('edit_staff/<staff_id>/', adminviews.edit_staff, name="edit_staff"),
    path('edit_staff_save/', adminviews.edit_staff_save, name="edit_staff_save"),
    path('delete_staff/<staff_id>/', adminviews.delete_staff, name="delete_staff"),
    path('add_project/', adminviews.add_project, name="add_project"),
    path('add_project_save/', adminviews.add_project_save, name="add_project_save"),
    path('manage_project/', adminviews.manage_project, name="manage_project"),
    path('edit_project/<project_id>/', adminviews.edit_project, name="edit_project"),
    path('edit_project_save/', adminviews.edit_project_save, name="edit_project_save"),
    path('delete_project/<project_id>/', adminviews.delete_project, name="delete_project"),
    path('manage_contract/', adminviews.manage_contract, name="manage_contract"),
    path('add_contract/', adminviews.add_contract, name="add_contract"),
    path('add_contract_save/', adminviews.add_contract_save, name="add_contract_save"),
    path('edit_contract/<contract_id>', adminviews.edit_contract, name="edit_contract"),
    path('edit_contract_save/', adminviews.edit_contract_save, name="edit_contract_save"),
    path('delete_contract/<contract_id>/', adminviews.delete_contract, name="delete_contract"),
    path('add_client/', adminviews.add_client, name="add_client"),
    path('add_client_save/', adminviews.add_client_save, name="add_client_save"),
    path('edit_client/<client_id>', adminviews.edit_client, name="edit_client"),
    path('edit_client_save/', adminviews.edit_client_save, name="edit_client_save"),
    path('manage_client/', adminviews.manage_client, name="manage_client"),
    path('delete_client/<client_id>/', adminviews.delete_client, name="delete_client"),
    path('add_task/', adminviews.add_task, name="add_task"),
    path('add_task_save/', adminviews.add_task_save, name="add_task_save"),
    path('manage_task/', adminviews.manage_task, name="manage_task"),
    path('edit_task/<task_id>/', adminviews.edit_task, name="edit_task"),
    path('edit_task_save/', adminviews.edit_task_save, name="edit_task_save"),
    path('delete_task/<task_id>/', adminviews.delete_task, name="delete_task"),
    path('add_supplier/', adminviews.add_supplier, name="add_supplier"),
    path('add_supplier_save/', adminviews.add_supplier_save, name="add_supplier_save"),
    path('manage_supplier/', adminviews.manage_supplier, name="manage_supplier"),
    path('edit_supplier/<supplier_id>', adminviews.edit_supplier, name="edit_supplier"),
    path('edit_supplier_save/', adminviews.edit_supplier_save, name="edit_supplier_save"),
    path('delete_supplier/<supplier_id>/', adminviews.delete_supplier, name="delete_supplier"),
    path('add_service/', adminviews.add_service, name="add_service"),
    path('add_service_save/', adminviews.add_service_save, name="add_service_save"),
    path('manage_service/', adminviews.manage_service, name="manage_service"),
    path('edit_service/<service_id>', adminviews.edit_service, name="edit_service"),
    path('edit_service_save/', adminviews.edit_service_save, name="edit_service_save"),
    path('delete_service/<service_id>/', adminviews.delete_service, name="delete_service"),
    path('add_part/', adminviews.add_part, name="add_part"),
    path('add_part_save/', adminviews.add_part_save, name="add_part_save"),
    path('manage_part/', adminviews.manage_part, name="manage_part"),
    path('edit_part/<part_id>', adminviews.edit_part, name="edit_part"),
    path('edit_part_save/', adminviews.edit_part_save, name="edit_part_save"),
    path('delete_part/<part_id>/', adminviews.delete_part, name="delete_part"),
    path('check_email_exist/', adminviews.check_email_exist, name="check_email_exist"),
    path('check_username_exist/', adminviews.check_username_exist, name="check_username_exist"),
    # path('student_feedback_message/', HodViews.student_feedback_message, name="student_feedback_message"),
    # path('student_feedback_message_reply/', HodViews.student_feedback_message_reply, name="student_feedback_message_reply"),
    # path('staff_feedback_message/', HodViews.staff_feedback_message, name="staff_feedback_message"),
    # path('staff_feedback_message_reply/', HodViews.staff_feedback_message_reply, name="staff_feedback_message_reply"),
    # path('student_leave_view/', HodViews.student_leave_view, name="student_leave_view"),
    # path('student_leave_approve/<leave_id>/', HodViews.student_leave_approve, name="student_leave_approve"),
    # path('student_leave_reject/<leave_id>/', HodViews.student_leave_reject, name="student_leave_reject"),
    # path('staff_leave_view/', HodViews.staff_leave_view, name="staff_leave_view"),
    # path('staff_leave_approve/<leave_id>/', HodViews.staff_leave_approve, name="staff_leave_approve"),
    # path('staff_leave_reject/<leave_id>/', HodViews.staff_leave_reject, name="staff_leave_reject"),
    # path('admin_view_attendance/', HodViews.admin_view_attendance, name="admin_view_attendance"),
    # path('admin_get_attendance_dates/', HodViews.admin_get_attendance_dates, name="admin_get_attendance_dates"),
    # path('admin_get_attendance_student/', HodViews.admin_get_attendance_student, name="admin_get_attendance_student"),
    path('admin_profile/', adminviews.admin_profile, name="admin_profile"),
    path('admin_profile_update/', adminviews.admin_profile_update, name="admin_profile_update"),
]